### ISSUE TITLE
[EPIC] Blossom User Management API and Dashboard

### ISSUE THREAD

**Issue by nikitawootten-nist** [usnistgov/blossom-nist-member#2]
# User Story
As the system owner of a (fake) agency using Blossom, I need to be able to create, modify, and change user fabric. identities and their association with the upstream identity provider (Login.gov).

Following the flow outlined in usnistgov/blossom-archived#92, we add new routes via an "Admin API Lambda" responsible for communicating with AWS Secrets Manager and the member's Fabric CA.

![Blossom Auth Flow(2)](https://user-images.githubusercontent.com/63109766/174909895-b579f417-1c49-427b-a1be-d7645ce29d12.png)

## Steps
- [ ] API routes exist to create, remove, or change attributes of a fabric identity as well as update the identity in AWS Secrets Manager
- [ ] The newly created routes are deployed via a lambda defined in the authentication Terraform configuration
- [ ] usnistgov/blossom-dashboard#27

## Dependencies
- usnistgov/blossom-archived#92: Needed to:
    - Provide the terraform configuration for the infrastructure surrounding the admin api (APIGW & secrets manager)
    - Define the connection to the external identity provider and how users will be associated with fabric identities
- usnistgov/blossom-archived#89: Needed to define the identity attributes needed to select from

## Resources
- https://hyperledger.github.io/fabric-sdk-node/release-1.4/FabricCAClient.html: The Hyperledger Fabric CA JS Client
- https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SecretsManager.html: The AWS Secrets Manager JS client
- https://docs.aws.amazon.com/lambda/latest/dg/lambda-typescript.html: An AWS doc page on setting up Lambda's with Typescript
- https://github.com/usnistgov/blossom/tree/nikitawootten-nist/issue92/identity/auth_lambda: The current state of the auth lambda being created in usnistgov/blossom-archived#92 *(note this branch will be deleted when merged)*
