### ISSUE TITLE
[EPIC] Bloss@m IAC enhancements

### ISSUE THREAD

**Issue by nikitawootten-nist** [usnistgov/blossom-nist-member#7]
After walking the DHS team through using our IAC, and introducing the IAC to more members, we have identified the following enhancements:

- [x] #4 
- [x] Wrap build & IAC in a Makefile

    This avoids the need to "double apply" changes to the website & lambdas.

    - [x] Automatically check for credential expiry before running Terraform commands

- [x] Define the Terraform state bucket
- [ ] Define Cognito resources in the IAC

    Currently all Cognito resources are manually defined, leading to additional setup & need to hardcode values.

- [ ] Define all hardcoded IAM policies
- [x] Fix S3 setup module utilizing deprecated resources
- [x] Populate Vite config with Terraform outputs
- [x] Specify the prefix for SSM secrets as an environment variable in the Lambda config
- [x] Build the connection profile programmatically
